### ISSUE TITLE
new password not shown in list of passwords

### ISSUE THREAD

**Issue by pern78** [KneeDeepInMud/fortGnox#35] opened 2023-10-04 15:06 UTC
Windows10/fortGnox1.0.7
Issue: Atfer creating a new password, the file is not shown in the lists of passwords until fortgnox has been restarted. 
Expected behaviour: fortGnox should show newly created password files immediately

**Comment by KneeDeepInMud** [comment] 2023-10-04 20:59
> Windows10/fortGnox1.0.7 Issue: Atfer creating a new password, the file is not shown in the lists of passwords until fortgnox has been restarted. Expected behaviour: fortGnox should show newly created password files immediately

is the `data directory`, i.e. the directory containing the gpg files, a native local hard disk drive, or any special filesystem (cryptomator, network drive etc?)?

**Comment by KneeDeepInMud** [comment] 2023-10-04 22:32
Issue could be reproduced on Windows using a mapped network drive. It looks like the `WatchService`  has issues on Windows in at least some Java versions, e.g. https://bugs.openjdk.org/browse/JDK-8227667

    java.io.IOException: Unzulässige Funktion.

        at java.base/sun.nio.fs.WindowsWatchService$Poller.implRegister(WindowsWatchService.java:434)
        at java.base/sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:265)
        at java.base/sun.nio.fs.WindowsWatchService$Poller.run(WindowsWatchService.java:596)
        at java.base/java.lang.Thread.run(Thread.java:835)


Thanks to @pern78 for reporting this :+1:

**Comment by KneeDeepInMud** [comment] 2023-10-04 22:34
Workaround: use `C:\users\...` as data directory until fixed

**Comment by KneeDeepInMud** [comment] 2023-10-21 11:23
Should be fixed in v1.0.8

**Closed by KneeDeepInMud** 2023-10-21 11:23 UTC
Labels: bug, good first issue, question
